# Generated by Django 3.2.23 on 2023-12-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrands',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('model', models.CharField(default=None, max_length=100)),
                ('year', models.IntegerField()),
                ('image', models.CharField(max_length=500)),
                ('new_or_pre_owned_or_upcoming', models.CharField(choices=[('new', 'New'), ('pre_owned', 'Pre_Owned'), ('up_coming', 'Up_Coming')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarOverview',
            fields=[
                ('carmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.carmodels')),
                ('varients', models.CharField(max_length=1000)),
                ('ex_showroom_price', models.FloatField()),
                ('milage', models.CharField(max_length=1000)),
                ('engine', models.CharField(max_length=1000)),
                ('transmission', models.CharField(max_length=1000)),
                ('seating_capacity', models.IntegerField()),
                ('colors', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('white', 'White'), ('other', 'Other')], max_length=20)),
                ('user_review', models.FloatField()),
                ('description', models.TextField()),
            ],
            bases=('web_app.carmodels',),
        ),
        migrations.CreateModel(
            name='PreOwnedCarsOverview',
            fields=[
                ('carmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.carmodels')),
                ('no_of_owners', models.IntegerField()),
                ('images', models.ImageField(upload_to='static/images/pre_owned_cars/')),
                ('price', models.FloatField()),
                ('drive_train', models.CharField(choices=[('awd', 'AWD'), ('rwd', 'RWD')], max_length=1000)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('cng', 'Cng'), ('ev', 'Ev')], max_length=1000)),
                ('engine', models.CharField(max_length=1000)),
                ('kilometer_reading', models.FloatField()),
                ('registration_year', models.IntegerField()),
                ('transmission', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('pin_code', models.IntegerField()),
                ('address', models.TextField()),
                ('headline', models.CharField(max_length=5000)),
            ],
            bases=('web_app.carmodels',),
        ),
        migrations.CreateModel(
            name='UpcomingCarOverview',
            fields=[
                ('caroverview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.caroverview')),
                ('expected_release_date', models.DateField()),
                ('images', models.ImageField(upload_to='static/images/upcoming_cars/')),
                ('expected_price_range', models.CharField(max_length=1000)),
            ],
            bases=('web_app.caroverview',),
        ),
    ]
