# Generated by Django 3.2.22 on 2023-11-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='CarBrands',
        #     fields=[
        #         ('sno', models.AutoField(primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('country', models.CharField(max_length=100)),
        #     ],
        # ),
    ]
