# Generated by Django 3.2.22 on 2023-11-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_carbrands'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('model', models.CharField(default=None, max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
