# Generated by Django 3.2.23 on 2023-12-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
