# Generated by Django 3.2.22 on 2023-11-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_carmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodels',
            name='image',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
