# Generated by Django 3.2.23 on 2023-12-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='caruser',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
