# Generated by Django 3.2.22 on 2023-11-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_caroverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodels',
            name='new_or_pre_owned',
            field=models.CharField(choices=[('new', 'New'), ('pre_owned', 'Pre_Owned')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
