# Generated by Django 3.2.22 on 2023-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_carmodels_new_or_pre_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroverview',
            name='kilometer_reading',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
