# Generated by Django 3.2.23 on 2023-12-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_preownedcarsoverview_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preownedcarsoverview',
            name='images',
            field=models.ImageField(upload_to='static/images/pre_owned_cars/'),
        ),
    ]
