# Generated by Django 3.2.23 on 2023-12-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_alter_preownedcarsoverview_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodels',
            name='new_or_pre_owned',
        ),
        migrations.AddField(
            model_name='carmodels',
            name='new_or_pre_owned_or_upcoming',
            field=models.CharField(choices=[('new', 'New'), ('pre_owned', 'Pre_Owned'), ('up_coming', 'Up_Coming')], default='new', max_length=100),
            preserve_default=False,
        ),
    ]
