# Generated by Django 3.2.23 on 2023-12-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_auto_20231206_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingCarOverview',
            fields=[
                ('caroverview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.caroverview')),
                ('expected_release_date', models.DateField()),
                ('images', models.ImageField(upload_to='static/images/upcoming_cars/')),
                ('expected_price_range', models.CharField(max_length=1000)),
            ],
            bases=('web_app.caroverview',),
        ),
    ]
