# Generated by Django 3.2.23 on 2023-12-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_upcomingcaroverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
                ('mobile_no', models.IntegerField(max_length=12)),
            ],
        ),
    ]
